#!/usr/bin/env python

import sys

#
# Grid map generator
#

if(len(sys.argv) < 5):
    sys.exit("Syntax: " + sys.argv[0] + " height width nodesH nodesW")

height = float(sys.argv[1])
width = float(sys.argv[2])
nodesByHeight = int(sys.argv[3])
nodesByWidth = int(sys.argv[4])

print('nodes:')

for i in range(1, nodesByWidth+1):
    for j in range(1, nodesByHeight+1):
        print("node{0},{1},{2}".format((i-1)*nodesByHeight + j, i*width/nodesByWidth, j*height/nodesByHeight))

print('edges:')

for i in range(1, nodesByWidth+1):
    for j in range(1, nodesByHeight+1):

        node = "node" + str((i-1)*nodesByHeight + j)
        left = ",node" + str((i-2)*nodesByHeight + j)
        up = ",node" + str((i-1)*nodesByHeight + j - 1)
        down = ",node" + str((i-1)*nodesByHeight + j + 1)
        right = ",node" + str(i*nodesByHeight + j)
        
        # Up-left corner
        # Also special cases (h=1 or w=1) are handled here
        if (i == 1 and j == 1):
            if not (nodesByWidth == 1 and nodesByHeight == 1):
                if (nodesByWidth == 1):
                    print(node + down)
                elif (nodesByHeight == 1):
                    print(node + right)
                else:
                    print(node + down + right)
        
        # Up-right corner
        elif (i == nodesByWidth and j == 1):
            print(node + left + down)

        # Bottom-left corner
        elif (i == 1 and j == nodesByHeight):
            print(node + up + right)

        # Bottom-right corner
        elif (i == nodesByWidth and j == nodesByHeight):
            print(node + left + up)

        # First line
        elif (j == 1):
            print(node + left + down + right)

        # First column
        elif (i == 1):
            print(node + up + down + right)

        # Last line
        elif (j == nodesByHeight):
            print(node + left + up + right)

        # Last column
        elif (i == nodesByWidth):
            print(node + left + up + down)

        # Other cases
        else:
            print(node + left + up + down + right)
